# Generated by Django 5.0.2 on 2024-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinfomation',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
